version: "3"

services:
    dall2-go-server:
        container_name: "dall2-server"
        build: ./server
        ports:
            - "8080:8080"
    dall2-front:
        container_name: "dall2_front"
        build: ./client
        ports:
            - "80:3000"
    dall2-fast-server:
        container_name: "dall2-fast-server"
        build: ./fast_server
        ports:
            - "8000:8000"
