version: "3"

services:
    # dall2-go-server:
    #     container_name: "dall2-server"
    #     build: ./server
    #     ports:
    #         - "8001:8080"
    dall2-front:
        container_name: "dall2-front"
        build: ./client
        ports:
            - "80:3000"
        networks:
            - "dall2-network"
    dall2-fast-server:
        container_name: "dall2-fast-server"
        build: ./fast-server
        ports:
            - "8000:8000"
        networks:
            - "dall2-network"

networks:
    dall2-network:
